### ISSUE TITLE
Include Snakemake in descriptor type enumerator

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/tool-registry-service-schemas#156]
We are currently finalizing support for GA4GH TES in Snakemake (see https://github.com/snakemake/snakemake/tree/integrate_tes_v2). A Snakemake WES is also in the works.

To allow integration with TRS as well, we would thus appreciate if `SMK` ([`.smk` is the official file extension for Snakemake files](https://github.com/github/linguist/pull/3953)) could be added to the `DescriptorType` schema:

```yaml
    DescriptorType:
      type: string
      description: The type of descriptor that represents this version of the tool
        (e.g. CWL, WDL, NFL, or GALAXY). Note that these files can also include
        associated Docker/container files  and test parameters that further
        describe a version of a tool.
      enum:
        - CWL
        - WDL
        - NFL
        - GALAXY
        - SNAKEMAKE
```

I'm happy to file a PR if I get a positive response on here.
