### ISSUE TITLE
Tool Descriptor relative path is not discoverable

### ISSUE THREAD

**Issue by delagoya** [ga4gh/tool-registry-service-schemas#20]
I do not think the values for following path are discoverable:

`/tools/{id}/versions/{version-id}/{type}/descriptor/{relative-path}`

I assume the intent is to be able to navigate to subsumed CWL files that are encoded in a main CWL file of a workflow description. Is that correct? If so then it should be documented.

**Comment by denis-yuen** [comment]
It is documented although we welcome making it more understandable since it doesn't seem to be right now.
 
We currently have 
```
/tools/{id}/versions/{version-id}/{type}/descriptor/{relative-path}:
    get:
      summary: Get additional tool descriptor files (CWL/WDL) relative to the main file
description: Returns additional CWL or WDL descriptors for the specified tool in the same or subdirectories
```
and 
```
        - name: relative-path
          in: path
          required: true
          type: string
description: A relative path to the additional file (same directory or subdirectories), for example 'foo.cwl' would return a 'foo.cwl' from the same directory as the main descriptor
```
https://github.com/ga4gh/tool-registry-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L203

It is true that the relative files aren't discoverable from the API directly, it would require knowledge of the language whether it be CWL or WDL.
