### ISSUE TITLE
Propose to remove  `ToolDockerfile.descriptor`

### ISSUE THREAD

**Issue by delagoya** [ga4gh/tool-registry-service-schemas#22]
Much like issue #21 having both a `descriptor` and `url` seems redundant and the `url` should be the canonical source. 

Both of these seems like an optimization for a particular implementation of a the Dockstore UI.

**Comment by denis-yuen** [comment]
Like #21 I think it makes sense to make `url` optional rather than the canonical source.

**Comment by garyluu** [comment]
Looks like descriptor isn't present in ToolDockerfile:
```
  ToolDockerfile:
    type: object
    description: A tool dockerfile is a document that describes how to build a particular Docker image.
    required:
      - dockerfile
    properties:
      dockerfile:
        type: string
        description: The dockerfile content for this tool.
      url:
        type: string
description: 'Optional url to the dockerfile used to build this image, should include version information, and can include
```
Just the dockerfile contents and the optional url
