### ISSUE TITLE
ToolVersion.url example correction

### ISSUE THREAD

**Issue by redmitry** [ga4gh/tool-registry-service-schemas#98]
Hello,

In the latest openapi.yaml
```
ToolVersion
    url:
        description: The URL for this tool in this registry.
        example: http://agora.broadinstitute.org/tools/123456/1
```

Shouldn't it be "ht<span>tp://agora.broadinstitute.org/tools/123456/**versions**/1" ?

Thank you,

Dmitry

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TRS-25)
┆Project Name: GA4GH tool-registry-service
┆Issue Number: TRS-25
